spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: erp-core
  profiles:
    active: dev # Default profile
  
  # Common configurations can go here
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    os:
      enabled: true
